In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("000006NS_20260301-145543.csv")

In [3]:
df

,type of insurance company,investment assets,quarter,"Investment assets of Swedish insurance companies, stock values, MSEK"
0,Life insurance companies,1. Cash at bank and in hand,2007K3,29690
1,Life insurance companies,1. Cash at bank and in hand,2007K4,35045
2,Life insurance companies,1. Cash at bank and in hand,2008K1,42981
3,Life insurance companies,1. Cash at bank and in hand,2008K2,30477
4,Life insurance companies,1. Cash at bank and in hand,2008K3,35902
...,...,...,...,...
10069,Non-life insurance companies,12. Total capital investments,2024K3,719180
10070,Non-life insurance companies,12. Total capital investments,2024K4,708298
10071,Non-life insurance companies,12. Total capital investments,2025K1,714023
10072,Non-life insurance companies,12. Total capital investments,2025K2,704574
10073,Non-life insurance companies,12. Total capital investments,2025K3,743195

In [4]:
df.head(10)

,type of insurance company,investment assets,quarter,"Investment assets of Swedish insurance companies, stock values, MSEK"
0,Life insurance companies,1. Cash at bank and in hand,2007K3,29690
1,Life insurance companies,1. Cash at bank and in hand,2007K4,35045
2,Life insurance companies,1. Cash at bank and in hand,2008K1,42981
3,Life insurance companies,1. Cash at bank and in hand,2008K2,30477
4,Life insurance companies,1. Cash at bank and in hand,2008K3,35902
5,Life insurance companies,1. Cash at bank and in hand,2008K4,59090
6,Life insurance companies,1. Cash at bank and in hand,2009K1,53613
7,Life insurance companies,1. Cash at bank and in hand,2009K2,44755
8,Life insurance companies,1. Cash at bank and in hand,2009K3,42767
9,Life insurance companies,1. Cash at bank and in hand,2009K4,45730

In [5]:
df.tail(10)

,type of insurance company,investment assets,quarter,"Investment assets of Swedish insurance companies, stock values, MSEK"
10064,Non-life insurance companies,12. Total capital investments,2023K2,689461
10065,Non-life insurance companies,12. Total capital investments,2023K3,675925
10066,Non-life insurance companies,12. Total capital investments,2023K4,690891
10067,Non-life insurance companies,12. Total capital investments,2024K1,721655
10068,Non-life insurance companies,12. Total capital investments,2024K2,707359
10069,Non-life insurance companies,12. Total capital investments,2024K3,719180
10070,Non-life insurance companies,12. Total capital investments,2024K4,708298
10071,Non-life insurance companies,12. Total capital investments,2025K1,714023
10072,Non-life insurance companies,12. Total capital investments,2025K2,704574
10073,Non-life insurance companies,12. Total capital investments,2025K3,743195

In [6]:
df.dtypes

type of insurance company                                               str
investment assets                                                       str
quarter                                                                 str
Investment assets of Swedish insurance companies, stock values, MSEK    str
dtype: object

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10074 entries, 0 to 10073
Data columns (total 4 columns):
 #   Column                                                                Non-Null Count  Dtype
---  ------                                                                --------------  -----
 0   type of insurance company                                             10074 non-null  str
 1   investment assets                                                     10074 non-null  str
 2   quarter                                                               10074 non-null  str
 3   Investment assets of Swedish insurance companies, stock values, MSEK  10074 non-null  str
dtypes: str(4)
memory usage: 314.9 KB

In [8]:
df.rename(columns={'Investment assets of Swedish insurance companies, stock values, MSEK':'stock values'},inplace=True)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10074 entries, 0 to 10073
Data columns (total 4 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   type of insurance company  10074 non-null  str
 1   investment assets          10074 non-null  str
 2   quarter                    10074 non-null  str
 3   stock values               10074 non-null  str
dtypes: str(4)
memory usage: 314.9 KB

In [12]:
df.loc[df['stock values'] == '..']

,type of insurance company,investment assets,quarter,stock values
1387,Life insurance companies,3.2.1 of which index-linked notes,2007K3,..
1388,Life insurance companies,3.2.1 of which index-linked notes,2007K4,..
1389,Life insurance companies,3.2.1 of which index-linked notes,2008K1,..
1390,Life insurance companies,3.2.1 of which index-linked notes,2008K2,..
1391,Life insurance companies,3.2.1 of which index-linked notes,2008K3,..
...,...,...,...,...
9857,Non-life insurance companies,10. Repurchase agreements,2008K1,..
9858,Non-life insurance companies,10. Repurchase agreements,2008K2,..
9859,Non-life insurance companies,10. Repurchase agreements,2008K3,..
9860,Non-life insurance companies,10. Repurchase agreements,2008K4,..
9861,Non-life insurance companies,10. Repurchase agreements,2009K1,..