In [33]:
import requests
import pandas as pd
from io import StringIO

url = "https://api.scb.se/OV0104/v1/doris/en/ssd/START/FM/FM0501/FM0501Tab04"

In [34]:
meta = requests.get(url).json()
print(meta)

{'title': 'Investment assets of Swedish insurance companies by type of insurance company, investment assets, observations and quarter', 'variables': [{'code': 'TypForetag', 'text': 'type of insurance company', 'values': ['1', '1.1', '1.2'], 'valueTexts': ['Total', 'Life insurance companies', 'Non-life insurance companies']}, {'code': 'Placeringstillgangar', 'text': 'investment assets', 'values': ['1', '1.1', '1.2', '2', '2.1', '2.2', '2.3', '2.3.1', '2.3.2', '2.3.3', '2.3.4', '2.3.5', '2.3.6', '2.3.7', '2.3.8', '2.4', '3', '3.1', '3.2', '3.2.1', '3.3', '3.3.1', '3.3.2', '3.3.3', '3.3.4', '3.3.5', '3.3.6', '3.3.7', '3.3.8', '3.3.9', '3.4', '4', '4.1', '4.2', '4.3', '4.4', '5', '6', '6.1', '6.2', '6.2.1', '6.2.2', '6.3', '6.4', '6.4.1', '6.4.2', '6.5', '6.6', '6.7', '7', '7.1', '7.2', '7.3', '7.3.1', '7.3.2', '7.3.3', '7.3.4', '7.3.5', '7.3.6', '7.3.7', '7.3.8', '7.4', '8', '8.1', '8.2', '9', '10', '11', '12'], 'valueTexts': ['1. Cash at bank and in hand', '1.1 Swedish banks', '1.2 Foreign banks', '2. Money market instruments', '2.1 Issued in SEK', '2.2 Issued in foreign currency', '2.3 Issued by Swedish borrowers', '2.3.1 Government', '2.3.2 Municipalities and regions', '2.3.3 Banks (MFI)', '2.3.4 Housing credit institutions (MFI)', '2.3.5 Other MFI', '2.3.6 Financial institutions (non-MFI)', '2.3.7 Non-financial enterprises', '2.3.8 Other Swedish borrowers', '2.4 Issued by foreign borrowers', '3. Bonds', '3.1 Issued in SEK', '3.2 Issued in foreign currency', '3.2.1   of which index-linked notes', '3.3 Issued by Swedish borrowers', '3.3.1 Index-linked treasury bonds', '3.3.2 Other government bonds', '3.3.3 Municipalities and regions', '3.3.4 Banks (MFI)', '3.3.5 Housing credit institutions (MFI)', '3.3.6 Other MFI', '3.3.7 Financial institutions (non-MFI)', '3.3.8 Non-financial enterprises', '3.3.9 Other Swedish borrowers', '3.4 Issued by foreign borrowers', '4. Debentures and convertible loans', '4.1 Swedish MFI', '4.2 Swedish financial institutions, non-MFI', '4.3 Other Swedish borrowers', '4.4 Foreign borrowers', '5. Accrued interest', '6. Shares and participations', '6.1   of which shares in wholly owned real estate co.', '6.2 Swedish shares', '6.2.1 Shares quoted', '6.2.2 Shares not quoted', '6.3 Foreign shares', '6.4 Investment funds', '6.4.1 Swedish', '6.4.2 Foreign', '6.5   of which funds in unit linked insurances', '6.6   of which investment in interest funds', '6.7 Options and other ownership shares', '7. Loans', '7.1 Issued in SEK', '7.2 Issued in foreign currency', '7.3 Issued by Swedish borrowers', '7.3.1 Government', '7.3.2 Municipalities and regions', '7.3.3 Banks (MFI)', '7.3.4 Housing credit institutions (MFI)', '7.3.5 Other MFI', '7.3.6 Financial institutions (non-MFI)', '7.3.7 Non-financial enterprises', '7.3.8 Other Swedish borrowers', '7.4 Issued by foreign borrowers', '8. Land and buildings', '8.1 Swedish', '8.2 Foreign', '9. Derivatives', '10. Repurchase agreements', '11. Other financial investments', '12. Total capital investments']}, {'code': 'ContentsCode', 'text': 'observations', 'values': ['000006NS', '000006NM'], 'valueTexts': ['Stock values, MSEK', 'Net transactions, MSEK']}, {'code': 'Tid', 'text': 'quarter', 'values': ['2007K3', '2007K4', '2008K1', '2008K2', '2008K3', '2008K4', '2009K1', '2009K2', '2009K3', '2009K4', '2010K1', '2010K2', '2010K3', '2010K4', '2011K1', '2011K2', '2011K3', '2011K4', '2012K1', '2012K2', '2012K3', '2012K4', '2013K1', '2013K2', '2013K3', '2013K4', '2014K1', '2014K2', '2014K3', '2014K4', '2015K1', '2015K2', '2015K3', '2015K4', '2016K1', '2016K2', '2016K3', '2016K4', '2017K1', '2017K2', '2017K3', '2017K4', '2018K1', '2018K2', '2018K3', '2018K4', '2019K1', '2019K2', '2019K3', '2019K4', '2020K1', '2020K2', '2020K3', '2020K4', '2021K1', '2021K2', '2021K3', '2021K4', '2022K1', '2022K2', '2022K3', '2022K4', '2023K1', '2023K2', '2023K3', '2023K4', '2024K1', '2024K2', '2024K3', '2024K4', '2025K1', '2025K2', '2025K3', '2025K4'], 'valueTexts': ['2007K3', '2007K4', '2008K1', '2008K2', '2008K3', '2008K4', '2009K1', '2009K2', '2009K3', '2009K4', '2010K1', '2010K2', '2010K3', '2010K4', '2011K1', '2011K2', '2011K3', '2011K4', '2012K1', '2012K2', '2012K3', '2012K4', '2013K1', '2013K2', '2013K3', '2013K4', '2014K1', '2014K2', '2014K3', '2014K4', '2015K1', '2015K2', '2015K3', '2015K4', '2016K1', '2016K2', '2016K3', '2016K4', '2017K1', '2017K2', '2017K3', '2017K4', '2018K1', '2018K2', '2018K3', '2018K4', '2019K1', '2019K2', '2019K3', '2019K4', '2020K1', '2020K2', '2020K3', '2020K4', '2021K1', '2021K2', '2021K3', '2021K4', '2022K1', '2022K2', '2022K3', '2022K4', '2023K1', '2023K2', '2023K3', '2023K4', '2024K1', '2024K2', '2024K3', '2024K4', '2025K1', '2025K2', '2025K3', '2025K4'], 'time': True}]}

In [ ]:
"""
Meta
{'title': 'Investment assets of Swedish insurance companies by type of insurance company, investment assets, observations and quarter', 
 'variables': [
     {'code': 'TypForetag', 
      'text': 'type of insurance company', 
      'values': ['1', '1.1', '1.2'], 
      'valueTexts': ['Total', 'Life insurance companies', 'Non-life insurance companies']
      }, 
      {'code': 'Placeringstillgangar', 
       'text': 'investment assets', 
       'values': ['1', '1.1', '1.2', 
                  '2', '2.1', '2.2', '2.3', '2.3.1', '2.3.2', '2.3.3', '2.3.4', '2.3.5', '2.3.6', '2.3.7', '2.3.8', '2.4', 
                  '3', '3.1', '3.2', '3.2.1', '3.3', '3.3.1', '3.3.2', '3.3.3', '3.3.4', '3.3.5', '3.3.6', '3.3.7', '3.3.8', '3.3.9', '3.4', 
                  '4', '4.1', '4.2', '4.3', '4.4', 
                  '5', 
                  '6', '6.1', '6.2', '6.2.1', '6.2.2', '6.3', '6.4', '6.4.1', '6.4.2', '6.5', '6.6', '6.7', 
                  '7', '7.1', '7.2', '7.3', '7.3.1', '7.3.2', '7.3.3', '7.3.4', '7.3.5', '7.3.6', '7.3.7', '7.3.8', '7.4', 
                  '8', '8.1', '8.2', 
                  '9', 
                  '10', 
                  '11', 
                  '12'], 
       'valueTexts': ['1. Cash at bank and in hand', '1.1 Swedish banks', '1.2 Foreign banks', 
                      '2. Money market instruments', '2.1 Issued in SEK', '2.2 Issued in foreign currency', '2.3 Issued by Swedish borrowers', '2.3.1 Government', '2.3.2 Municipalities and regions', '2.3.3 Banks (MFI)', '2.3.4 Housing credit institutions (MFI)', '2.3.5 Other MFI', '2.3.6 Financial institutions (non-MFI)', '2.3.7 Non-financial enterprises', '2.3.8 Other Swedish borrowers', '2.4 Issued by foreign borrowers', 
                      '3. Bonds', '3.1 Issued in SEK', '3.2 Issued in foreign currency', '3.2.1   of which index-linked notes', '3.3 Issued by Swedish borrowers', '3.3.1 Index-linked treasury bonds', '3.3.2 Other government bonds', '3.3.3 Municipalities and regions', '3.3.4 Banks (MFI)', '3.3.5 Housing credit institutions (MFI)', '3.3.6 Other MFI', '3.3.7 Financial institutions (non-MFI)', '3.3.8 Non-financial enterprises', '3.3.9 Other Swedish borrowers', '3.4 Issued by foreign borrowers', 
                      '4. Debentures and convertible loans', '4.1 Swedish MFI', '4.2 Swedish financial institutions, non-MFI', '4.3 Other Swedish borrowers', '4.4 Foreign borrowers', 
                      '5. Accrued interest', 
                      '6. Shares and participations', '6.1   of which shares in wholly owned real estate co.', '6.2 Swedish shares', '6.2.1 Shares quoted', '6.2.2 Shares not quoted', '6.3 Foreign shares', '6.4 Investment funds', '6.4.1 Swedish', '6.4.2 Foreign', '6.5   of which funds in unit linked insurances', '6.6   of which investment in interest funds', '6.7 Options and other ownership shares', 
                      '7. Loans', '7.1 Issued in SEK', '7.2 Issued in foreign currency', '7.3 Issued by Swedish borrowers', '7.3.1 Government', '7.3.2 Municipalities and regions', '7.3.3 Banks (MFI)', '7.3.4 Housing credit institutions (MFI)', '7.3.5 Other MFI', '7.3.6 Financial institutions (non-MFI)', '7.3.7 Non-financial enterprises', '7.3.8 Other Swedish borrowers', '7.4 Issued by foreign borrowers', 
                      '8. Land and buildings', '8.1 Swedish', '8.2 Foreign', 
                      '9. Derivatives', 
                      '10. Repurchase agreements', 
                      '11. Other financial investments', 
                      '12. Total capital investments']},
         {'code': 'ContentsCode', 'text': 'observations', 
          'values': ['000006NS', '000006NM'], 
          'valueTexts': ['Stock values, MSEK', 'Net transactions, MSEK']}, 
         {'code': 'Tid', 
          'text': 'quarter', 
          'values': ['2007K3', '2007K4', 
                     '2008K1', '2008K2', '2008K3', '2008K4', 
                     '2009K1', '2009K2', '2009K3', '2009K4', 
                     '2010K1', '2010K2', '2010K3', '2010K4', 
                     '2011K1', '2011K2', '2011K3', '2011K4', 
                     '2012K1', '2012K2', '2012K3', '2012K4', 
                     '2013K1', '2013K2', '2013K3', '2013K4', 
                     '2014K1', '2014K2', '2014K3', '2014K4', 
                     '2015K1', '2015K2', '2015K3', '2015K4', 
                     '2016K1', '2016K2', '2016K3', '2016K4', 
                     '2017K1', '2017K2', '2017K3', '2017K4', 
                     '2018K1', '2018K2', '2018K3', '2018K4', 
                     '2019K1', '2019K2', '2019K3', '2019K4', 
                     '2020K1', '2020K2', '2020K3', '2020K4', 
                     '2021K1', '2021K2', '2021K3', '2021K4', 
                     '2022K1', '2022K2', '2022K3', '2022K4', 
                     '2023K1', '2023K2', '2023K3', '2023K4', 
                     '2024K1', '2024K2', '2024K3', '2024K4', 
                     '2025K1', '2025K2', '2025K3', '2025K4'], 
          'valueTexts': ['2007K3', '2007K4', 
                         '2008K1', '2008K2', '2008K3', '2008K4', 
                         '2009K1', '2009K2', '2009K3', '2009K4', 
                         '2010K1', '2010K2', '2010K3', '2010K4', 
                         '2011K1', '2011K2', '2011K3', '2011K4', 
                         '2012K1', '2012K2', '2012K3', '2012K4', 
                         '2013K1', '2013K2', '2013K3', '2013K4', 
                         '2014K1', '2014K2', '2014K3', '2014K4', 
                         '2015K1', '2015K2', '2015K3', '2015K4', 
                         '2016K1', '2016K2', '2016K3', '2016K4', 
                         '2017K1', '2017K2', '2017K3', '2017K4', 
                         '2018K1', '2018K2', '2018K3', '2018K4', 
                         '2019K1', '2019K2', '2019K3', '2019K4', 
                         '2020K1', '2020K2', '2020K3', '2020K4', 
                         '2021K1', '2021K2', '2021K3', '2021K4', 
                         '2022K1', '2022K2', '2022K3', '2022K4', 
                         '2023K1', '2023K2', '2023K3', '2023K4', 
                         '2024K1', '2024K2', '2024K3', '2024K4', 
                         '2025K1', '2025K2', '2025K3', '2025K4'], 
          'time': True}]}
"""

"\n{'title': 'Investment assets of Swedish insurance companies by type of insurance company, investment assets, observations and quarter', \n 'variables': [\n     {'code': 'TypForetag', \n      'text': 'type of insurance company', \n      'values': ['1', '1.1', '1.2'], \n      'valueTexts': ['Total', 'Life insurance companies', 'Non-life insurance companies']\n      }, \n      {'code': 'Placeringstillgangar', \n       'text': 'investment assets', \n       'values': ['1', '1.1', '1.2', \n                  '2', '2.1', '2.2', '2.3', '2.3.1', '2.3.2', '2.3.3', '2.3.4', '2.3.5', '2.3.6', '2.3.7', '2.3.8', '2.4', \n                  '3', '3.1', '3.2', '3.2.1', '3.3', '3.3.1', '3.3.2', '3.3.3', '3.3.4', '3.3.5', '3.3.6', '3.3.7', '3.3.8', '3.3.9', '3.4', \n                  '4', '4.1', '4.2', '4.3', '4.4', \n                  '5', \n                  '6', '6.1', '6.2', '6.2.1', '6.2.2', '6.3', '6.4', '6.4.1', '6.4.2', '6.5', '6.6', '6.7', \n                  '7', '7.1', '7.2', '7.3', '7.3.1', '7.3.2', '7.3.3', '7.3.4', '7.3.5', '7.3.6', '7.3.7', '7.3.8', '7.4', \n                  '8', '8.1', '8.2', \n                  '9', \n                  '10', \n                  '11', \n                  '12'], \n       'valueTexts': ['1. Cash at bank and in hand', '1.1 Swedish banks', '1.2 Foreign banks', \n                      '2. Money market instruments', '2.1 Issued in SEK', '2.2 Issued in foreign currency', '2.3 Issued by Swedish borrowers', '2.3.1 Government', '2.3.2 Municipalities and regions', '2.3.3 Banks (MFI)', '2.3.4 Housing credit institutions (MFI)', '2.3.5 Other MFI', '2.3.6 Financial institutions (non-MFI)', '2.3.7 Non-financial enterprises', '2.3.8 Other Swedish borrowers', '2.4 Issued by foreign borrowers', \n                      '3. Bonds', '3.1 Issued in SEK', '3.2 Issued in foreign currency', '3.2.1   of which index-linked notes', '3.3 Issued by Swedish borrowers', '3.3.1 Index-linked treasury bonds', '3.3.2 Other government bonds', '3.3.3 Municipalities and regions', '3.3.4 Banks (MFI)', '3.3.5 Housing credit institutions (MFI)', '3.3.6 Other MFI', '3.3.7 Financial institutions (non-MFI)', '3.3.8 Non-financial enterprises', '3.3.9 Other Swedish borrowers', '3.4 Issued by foreign borrowers', \n                      '4. Debentures and convertible loans', '4.1 Swedish MFI', '4.2 Swedish financial institutions, non-MFI', '4.3 Other Swedish borrowers', '4.4 Foreign borrowers', \n                      '5. Accrued interest', \n                      '6. Shares and participations', '6.1   of which shares in wholly owned real estate co.', '6.2 Swedish shares', '6.2.1 Shares quoted', '6.2.2 Shares not quoted', '6.3 Foreign shares', '6.4 Investment funds', '6.4.1 Swedish', '6.4.2 Foreign', '6.5   of which funds in unit linked insurances', '6.6   of which investment in interest funds', '6.7 Options and other ownership shares', \n                      '7. Loans', '7.1 Issued in SEK', '7.2 Issued in foreign currency', '7.3 Issued by Swedish borrowers', '7.3.1 Government', '7.3.2 Municipalities and regions', '7.3.3 Banks (MFI)', '7.3.4 Housing credit institutions (MFI)', '7.3.5 Other MFI', '7.3.6 Financial institutions (non-MFI)', '7.3.7 Non-financial enterprises', '7.3.8 Other Swedish borrowers', '7.4 Issued by foreign borrowers', \n                      '8. Land and buildings', '8.1 Swedish', '8.2 Foreign', \n                      '9. Derivatives', \n                      '10. Repurchase agreements', \n                      '11. Other financial investments', \n                      '12. Total capital investments']},\n         {'code': 'ContentsCode', 'text': 'observations', \n          'values': ['000006NS', '000006NM'], \n          'valueTexts': ['Stock values, MSEK', 'Net transactions, MSEK']}, \n         {'code': 'Tid', \n          'text': 'quarter', \n          'values': ['2007K3', '2007K4', \n                     '2008K1', '2008K2', '2008K3', '2008K4', \n                     '2009K1', '2009K2', '2009K3', '2009K4', \n                     '2010K1', '2010K2', '2010K3', '2010K4', \n                     '2011K1', '2011K2', '2011K3', '2011K4', \n                     '2012K1', '2012K2', '2012K3', '2012K4', \n                     '2013K1', '2013K2', '2013K3', '2013K4', \n                     '2014K1', '2014K2', '2014K3', '2014K4', \n                     '2015K1', '2015K2', '2015K3', '2015K4', \n                     '2016K1', '2016K2', '2016K3', '2016K4', \n                     '2017K1', '2017K2', '2017K3', '2017K4', \n                     '2018K1', '2018K2', '2018K3', '2018K4', \n                     '2019K1', '2019K2', '2019K3', '2019K4', \n                     '2020K1', '2020K2', '2020K3', '2020K4', \n                     '2021K1', '2021K2', '2021K3', '2021K4', \n                     '2022K1', '2022K2', '2022K3', '2022K4', \n                     '2023K1', '2023K2', '2023K3', '2023K4', \n                     '2024K1', '2024K2', '2024K3', '2024K4', \n                     '2025K1', '2025K2', '2025K3', '2025K4'], \n          'valueTexts': ['2007K3', '2007K4', \n                         '2008K1', '2008K2', '2008K3', '2008K4', \n                         '2009K1', '2009K2', '2009K3', '2009K4', \n                         '2010K1', '2010K2', '2010K3', '2010K4', \n                         '2011K1', '2011K2', '2011K3', '2011K4', \n                         '2012K1', '2012K2', '2012K3', '2012K4', \n                         '2013K1', '2013K2', '2013K3', '2013K4', \n                         '2014K1', '2014K2', '2014K3', '2014K4', \n                         '2015K1', '2015K2', '2015K3', '2015K4', \n                         '2016K1', '2016K2', '2016K3', '2016K4', \n                         '2017K1', '2017K2', '2017K3', '2017K4', \n                         '2018K1', '2018K2', '2018K3', '2018K4', \n                         '2019K1', '2019K2', '2019K3', '2019K4', \n                         '2020K1', '2020K2', '2020K3', '2020K4', \n                         '2021K1', '2021K2', '2021K3', '2021K4', \n                         '2022K1', '2022K2', '2022K3', '2022K4', \n                         '2023K1', '2023K2', '2023K3', '2023K4', \n                         '2024K1', '2024K2', '2024K3', '2024K4', \n                         '2025K1', '2025K2', '2025K3', '2025K4'], \n          'time': True}]}\n"

In [36]:
query = {
  "query": [
    {
      "code": "TypForetag",
      "selection": {"filter": "item", "values": ["1.1"]}
    },
    {
      "code": "Placeringstillgangar",
      "selection": {"filter": "item", "values": ["1","2","3","4","5","6","7","8","9","10","11"]}
    },
    {
      "code": "ContentsCode",
      "selection": {"filter": "item", "values": ["000006NS"]}
    },
    {
      "code": "Tid",
      "selection": {"filter": "all", "values": ["*"]}
    }
  ],
  "response": {"format": "csv"}
}

In [37]:
response = requests.post(url, json=query)

df = pd.read_csv(StringIO(response.text), sep=",")
print(df)

   type of insurance company                    investment assets  \
0   Life insurance companies          1. Cash at bank and in hand
1   Life insurance companies          2. Money market instruments
2   Life insurance companies                             3. Bonds
3   Life insurance companies  4. Debentures and convertible loans
4   Life insurance companies                  5. Accrued interest
5   Life insurance companies         6. Shares and participations
6   Life insurance companies                             7. Loans
7   Life insurance companies                8. Land and buildings
8   Life insurance companies                       9. Derivatives
9   Life insurance companies            10. Repurchase agreements
10  Life insurance companies      11. Other financial investments

   Stock values, MSEK 2007K3 Stock values, MSEK 2007K4  \
0                      29690                     35045
1                      86510                     74642
2                     745131                    767257
3                       9316                      9284
4                      14982                     14311
5                    1152535                   1128415
6                      40215                     39057
7                      57855                     60009
8                         ..                        ..
9                         ..                        ..
10                     13697                     17895

   Stock values, MSEK 2008K1 Stock values, MSEK 2008K2  \
0                      42981                     30477
1                      45668                     48685
2                     810605                    814354
3                       9170                      8839
4                      17123                     15523
5                    1031481                   1008276
6                      38974                     35782
7                      57522                     56175
8                         ..                        ..
9                         ..                        ..
10                     26687                     15765

   Stock values, MSEK 2008K3 Stock values, MSEK 2008K4  \
0                      35902                     59090
1                      44890                     30747
2                     830498                    901685
3                      11242                     13548
4                      16355                     15736
5                     951288                    834375
6                      35437                     34950
7                      54130                     49891
8                         ..                        ..
9                         ..                        ..
10                      6268                      6911

   Stock values, MSEK 2009K1  Stock values, MSEK 2009K2  ...  \
0                      53613                      44755  ...
1                      36704                      27861  ...
2                     873875                     881320  ...
3                      13235                      15065  ...
4                      17745                      14993  ...
5                     819573                     969484  ...
6                      37252                      37980  ...
7                      49562                      48482  ...
8                         ..                      14423  ...
9                         ..                       1924  ...
10                     15450                      14831  ...

    Stock values, MSEK 2023K3  Stock values, MSEK 2023K4  \
0                      120374                     140326
1                       63837                     101743
2                     1156630                    1189335
3                       26354                      28333
4                       10027                       9983
5                     4425952                    4630526
6                      134727                     126309
7                       84640                      59401
8                       38986                      79209
9                       33105                      34303
10                      38294                      15626

    Stock values, MSEK 2024K1  Stock values, MSEK 2024K2  \
0                      120916                     130137
1                       96388                      71343
2                     1219160                    1261635
3                       30432                      30529
4                       12851                      12321
5                     5062092                    5168616
6                      118051                     118720
7                       58807                      56588
8                       16253                      22813
9                       28627                      17689
10                      44821                      17390

    Stock values, MSEK 2024K3  Stock values, MSEK 2024K4  \
0                      140187                     107246
1                       69156                      59893
2                     1297328                    1338767
3                       28072                      27273
4                       12880                      13339
5                     5281655                    5355458
6                      124785                     120005
7                       56419                      57670
8                       36810                      15834
9                       14232                      14403
10                      27037                      17704

    Stock values, MSEK 2025K1  Stock values, MSEK 2025K2  \
0                      154216                     139796
1                       63757                      95058
2                     1336173                    1360312
3                       27390                      27254
4                       14396                      13623
5                     5050062                    5288776
6                      128854                     129446
7                       55237                      53986
8                       70308                      34013
9                        6676                        473
10                      26448                      14790

    Stock values, MSEK 2025K3  Stock values, MSEK 2025K4
0                      136104                     130226
1                      100241                      82763
2                     1366687                    1398402
3                       25317                      25395
4                       15861                      14536
5                     5502280                    5645195
6                      122091                     126219
7                       54280                      54423
8                       26356                      35929
9                        1148                       5000
10                     105352                       8930

[11 rows x 76 columns]

In [38]:
df.head()

,type of insurance company,investment assets,"Stock values, MSEK 2007K3","Stock values, MSEK 2007K4","Stock values, MSEK 2008K1","Stock values, MSEK 2008K2","Stock values, MSEK 2008K3","Stock values, MSEK 2008K4","Stock values, MSEK 2009K1","Stock values, MSEK 2009K2",...,"Stock values, MSEK 2023K3","Stock values, MSEK 2023K4","Stock values, MSEK 2024K1","Stock values, MSEK 2024K2","Stock values, MSEK 2024K3","Stock values, MSEK 2024K4","Stock values, MSEK 2025K1","Stock values, MSEK 2025K2","Stock values, MSEK 2025K3","Stock values, MSEK 2025K4"
0,Life insurance companies,1. Cash at bank and in hand,29690,35045,42981,30477,35902,59090,53613,44755,...,120374,140326,120916,130137,140187,107246,154216,139796,136104,130226
1,Life insurance companies,2. Money market instruments,86510,74642,45668,48685,44890,30747,36704,27861,...,63837,101743,96388,71343,69156,59893,63757,95058,100241,82763
2,Life insurance companies,3. Bonds,745131,767257,810605,814354,830498,901685,873875,881320,...,1156630,1189335,1219160,1261635,1297328,1338767,1336173,1360312,1366687,1398402
3,Life insurance companies,4. Debentures and convertible loans,9316,9284,9170,8839,11242,13548,13235,15065,...,26354,28333,30432,30529,28072,27273,27390,27254,25317,25395
4,Life insurance companies,5. Accrued interest,14982,14311,17123,15523,16355,15736,17745,14993,...,10027,9983,12851,12321,12880,13339,14396,13623,15861,14536

In [39]:
df.tail()

,type of insurance company,investment assets,"Stock values, MSEK 2007K3","Stock values, MSEK 2007K4","Stock values, MSEK 2008K1","Stock values, MSEK 2008K2","Stock values, MSEK 2008K3","Stock values, MSEK 2008K4","Stock values, MSEK 2009K1","Stock values, MSEK 2009K2",...,"Stock values, MSEK 2023K3","Stock values, MSEK 2023K4","Stock values, MSEK 2024K1","Stock values, MSEK 2024K2","Stock values, MSEK 2024K3","Stock values, MSEK 2024K4","Stock values, MSEK 2025K1","Stock values, MSEK 2025K2","Stock values, MSEK 2025K3","Stock values, MSEK 2025K4"
6,Life insurance companies,7. Loans,40215,39057,38974,35782,35437,34950,37252,37980,...,134727,126309,118051,118720,124785,120005,128854,129446,122091,126219
7,Life insurance companies,8. Land and buildings,57855,60009,57522,56175,54130,49891,49562,48482,...,84640,59401,58807,56588,56419,57670,55237,53986,54280,54423
8,Life insurance companies,9. Derivatives,..,..,..,..,..,..,..,14423,...,38986,79209,16253,22813,36810,15834,70308,34013,26356,35929
9,Life insurance companies,10. Repurchase agreements,..,..,..,..,..,..,..,1924,...,33105,34303,28627,17689,14232,14403,6676,473,1148,5000
10,Life insurance companies,11. Other financial investments,13697,17895,26687,15765,6268,6911,15450,14831,...,38294,15626,44821,17390,27037,17704,26448,14790,105352,8930